# Generated by Django 5.1.6 on 2025-03-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_secondary_group_exercise_secondary_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
