# Generated by Django 5.1.6 on 2025-03-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_musclegroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='gif_link_front',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='gif_link_side',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
