# Generated by Django 5.1.6 on 2025-03-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_exercise_gif_link_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
