# Generated by Django 5.1.7 on 2025-04-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
