# Generated by Django 5.1.7 on 2025-04-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_trainingprogram_trainingsession_programexercise"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programexercise",
            options={},
        ),
        migrations.AlterModelOptions(
            name="trainingsession",
            options={},
        ),
        migrations.RemoveField(
            model_name="programexercise",
            name="order",
        ),
        migrations.RemoveField(
            model_name="trainingsession",
            name="order",
        ),
    ]
