# Generated by Django 5.1.7 on 2025-04-18 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="programexercise",
            name="custom_exercise",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="programexercise",
            name="custom_muscle_group",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="programexercise",
            name="muscle_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="program_muscle_group",
                to="api.musclegroup",
            ),
        ),
    ]
