# Generated by Django 5.1.7 on 2025-04-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_programexercise_custom_exercise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programexercise",
            name="sequence",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="programexercise",
            name="sets",
            field=models.IntegerField(),
        ),
    ]
