# Generated by Django 5.1.7 on 2025-04-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_programexercise_sequence_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programexercise",
            old_name="custom_exercise",
            new_name="custom_exercise_title",
        ),
        migrations.RemoveField(
            model_name="programexercise",
            name="custom_muscle_group",
        ),
        migrations.AddField(
            model_name="programexercise",
            name="is_custom_muscle_group",
            field=models.BooleanField(default=False),
        ),
    ]
