# Generated by Django 5.1.7 on 2025-04-21 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0020_rename_custom_exercise_programexercise_custom_exercise_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="programexercise",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="program_exercises",
                to="api.exercise",
            ),
        ),
    ]
