# Generated by Django 5.1.7 on 2025-04-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_programexercise_exercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programexercise",
            name="custom_exercise_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
