# Generated by Django 5.2 on 2025-05-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_programexercise_custom_exercise_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingprogram",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("scheduled", "Scheduled"),
                    ("current", "Current"),
                    ("archived", "Archived"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trainingprogram",
            name="mode",
            field=models.CharField(
                choices=[("template", "Template"), ("create", "Assigned")],
                max_length=20,
            ),
        ),
    ]
