version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'

  # docker compose up
  # docker-compose -f docker-compose.dev.yml -p alishfitness_dev up --build
  # docker compose down
  # docker-compose -f docker-compose.dev.yml -p alishfitness_dev down
