version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'

  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'

  database:
    image: postgres:17
    ports:
      - '5432:5432'
