# Generated by Django 5.2 on 2025-06-05 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "training_program",
            "0004_rename_schedule_array_trainingprogram_schedule_data",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training_program.trainingsession",
                    ),
                ),
                (
                    "training_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training_program.trainingprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SetLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.PositiveIntegerField(blank=True, null=True)),
                ("reps", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training_program.trainingexercise",
                    ),
                ),
                (
                    "session_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_logs",
                        to="session_logging.sessionlog",
                    ),
                ),
            ],
        ),
    ]
