# Generated by Django 5.2 on 2025-06-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session_logging", "0001_initial"),
        (
            "training_program",
            "0004_rename_schedule_array_trainingprogram_schedule_data",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="setlog",
            name="set_number",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="setlog",
            unique_together={("session_log", "exercise", "set_number")},
        ),
    ]
