# Generated by Django 5.2.3 on 2025-06-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session_logging", "0002_setlog_set_number_alter_setlog_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
