# Generated by Django 5.2.3 on 2025-06-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("session_logging", "0003_sessionlog_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessionlog",
            old_name="completed_at",
            new_name="created_at",
        ),
    ]
