# Generated by Django 5.2.3 on 2025-06-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session_logging", "0004_rename_completed_at_sessionlog_created_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="setlog",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="setlog",
            name="sequence",
            field=models.CharField(default="A", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="setlog",
            unique_together={("session_log", "set_number", "sequence")},
        ),
    ]
