# Generated by Django 5.2.3 on 2025-07-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session_logging", "0006_alter_setlog_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionlog",
            name="next_schedule_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
