# Generated by Django 5.2.3 on 2025-07-04 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session_logging", "0007_sessionlog_next_schedule_data"),
        ("training_program", "0005_auto_20250704_1431"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionlog",
            name="next_schedule_data",
        ),
        migrations.AddField(
            model_name="sessionlog",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sessionlog",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="training_program.trainingsession",
            ),
        ),
        migrations.AlterField(
            model_name="sessionlog",
            name="training_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="training_program.trainingprogram",
            ),
        ),
        migrations.AlterField(
            model_name="setlog",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="training_program.trainingexercise",
            ),
        ),
        migrations.AlterField(
            model_name="setlog",
            name="set_number",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
