# Generated by Django 5.2.3 on 2025-07-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session_logging", "0008_remove_sessionlog_next_schedule_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionlog",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
