# Generated by Django 5.2 on 2025-05-17 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_title", models.CharField(max_length=255)),
                (
                    "mode",
                    models.CharField(
                        choices=[("template", "Template"), ("create", "Assigned")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("current", "Current"),
                            ("archived", "Archived"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("activation_date", models.DateField(blank=True, null=True)),
                ("schedule_array", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProgramExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_custom_muscle_group", models.BooleanField(default=False)),
                (
                    "custom_exercise_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sequence", models.CharField(max_length=10)),
                ("sets", models.IntegerField()),
                ("reps", models.CharField(max_length=50)),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_exercises",
                        to="exercise.exercise",
                    ),
                ),
                (
                    "muscle_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_muscle_group",
                        to="exercise.musclegroup",
                    ),
                ),
            ],
        ),
    ]
