# Generated by Django 5.2 on 2025-05-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0001_initial"),
        ("training_program", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProgramExercise",
            new_name="TrainingExercise",
        ),
        migrations.AlterField(
            model_name="trainingprogram",
            name="mode",
            field=models.CharField(
                choices=[("template", "Template"), ("assigned", "Assigned")],
                max_length=20,
            ),
        ),
    ]
