# Generated by Django 5.2 on 2025-06-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training_program", "0003_rename_programexercise_trainingexercise_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainingprogram",
            old_name="schedule_array",
            new_name="schedule_data",
        ),
    ]
