# Generated by Django 5.2.3 on 2025-07-04 11:31

from django.db import migrations

def convert_schedule_data(apps, schema_editor):
    TrainingProgram = apps.get_model('training_program', 'TrainingProgram')
    for program in TrainingProgram.objects.all():
        old_schedule = program.schedule_data
        if isinstance(old_schedule, list) and old_schedule and isinstance(old_schedule[0], int):
            new_schedule = [
                {"order": idx + 1, "session_id": session_id}
                for idx, session_id in enumerate(old_schedule)
            ]
            program.schedule_data = new_schedule
            program.save(update_fields=["schedule_data"])

class Migration(migrations.Migration):

    dependencies = [
        (
            "training_program",
            "0004_rename_schedule_array_trainingprogram_schedule_data",
        ),
    ]

    operations = [
        migrations.RunPython(convert_schedule_data),
    ]

